# Generated by Django 4.1.7 on 2023-03-04 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tin',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Баланс на счету'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,12}$')], verbose_name='ИНН пользователя'),
        ),
    ]
