# Generated by Django 4.1.7 on 2023-03-04 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bill_remove_user_tin_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,12}$')], verbose_name='ИНН пользователя'),
        ),
    ]
